login:
  path: /login
  methods: ["POST"]

refresh_token:
  path: /token/refresh

logout:
  path: /logout

api_send_mail:
  path: /api/send-mail-pdf
  controller: App\Controller\SendEmailController
  methods: [POST]

api_interventions:
  path: /api/interventions
  controller: App\Controller\CreateInterventionsController
  methods: [ POST ]