login:
  path: /login
  methods: ["POST"]

refresh_token:
  path: /token/refresh

logout:
  path: /logout

api_send_mail:
  path: /api/send-mail
  controller: App\Controller\SendEmailController
  methods: [POST]
